development:
  adapter: sqlite3
  database: db/stringer.sqlite

test:
  adapter: sqlite3
  database: db/stringer_test.sqlite

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: rss_reader
  username: rss_reader
  password: ****
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
